---
version: "3.2"
services:
  web:
    image: "${IMAGE_NAME:-portal_web}:${TAG:-latest}"
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - debian_repo="${DEBIAN_REPO:-http://dl.bintray.com/v1/content/uwcirg/${BINTRAY_DEB_REPO:-true_nth}}"

  builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile.build
    environment:
      - GIT_REPO=${GIT_REPO:-/mnt/git_repo}
      - BRANCH=${BRANCH:-develop}
    volumes:
      - source: ../debian/artifacts
        target: /tmp/artifacts
        type: bind
      - source: ..
        target: "${GIT_REPO:-/mnt/git_repo}"
        type: bind
        read_only: true

volumes: {}
